/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

import * as npm from './../data/npm';
import { Context } from '@trygql/api/context';
import { core, connectionPluginCore } from 'nexus';
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.CommonInputFieldConfig<TypeName, FieldName>
    ): void; // "DateTime";
    /**
     * A field whose value conforms to the standard internet email address format as specified in RFC822: https://www.w3.org/Protocols/rfc822/.
     */
    email<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.CommonInputFieldConfig<TypeName, FieldName>
    ): void; // "EmailAddress";
    /**
     * A field whose value conforms to the standard URL format as specified in RFC3986: https://www.ietf.org/rfc/rfc3986.txt.
     */
    url<FieldName extends string>(
      fieldName: FieldName,
      opts?: core.CommonInputFieldConfig<TypeName, FieldName>
    ): void; // "URL";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    dateTime<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "DateTime";
    /**
     * A field whose value conforms to the standard internet email address format as specified in RFC822: https://www.w3.org/Protocols/rfc822/.
     */
    email<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "EmailAddress";
    /**
     * A field whose value conforms to the standard URL format as specified in RFC3986: https://www.ietf.org/rfc/rfc3986.txt.
     */
    url<FieldName extends string>(
      fieldName: FieldName,
      ...opts: core.ScalarOutSpread<TypeName, FieldName>
    ): void; // "URL";
    /**
     * Adds a Relay-style connection to the type, with numerous options for configuration
     *
     * @see https://nexusjs.org/docs/plugins/connection
     */
    connectionField<FieldName extends string>(
      fieldName: FieldName,
      config: connectionPluginCore.ConnectionFieldConfig<TypeName, FieldName>
    ): void;
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {}

export interface NexusGenEnums {}

export interface NexusGenScalars {
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
  DateTime: any;
  EmailAddress: any;
  URL: any;
}

export interface NexusGenObjects {
  Distributable: npm.Distributable;
  External: npm.External;
  File: {
    // root type
    contentType?: string | null; // String
    integrity?: string | null; // String
    lastModified?: NexusGenScalars['DateTime'] | null; // DateTime
    path: string; // String!
    size?: number | null; // Int
    url?: NexusGenScalars['URL'] | null; // URL
  };
  Package: npm.Package;
  PackageConnection: {
    // root type
    edges?: Array<NexusGenRootTypes['PackageEdge'] | null> | null; // [PackageEdge]
    nodes?: Array<NexusGenRootTypes['Package'] | null> | null; // [Package]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  };
  PackageEdge: {
    // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['Package'] | null; // Package
  };
  PageInfo: {
    // root type
    endCursor?: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor?: string | null; // String
  };
  Query: {};
  Tag: {
    // root type
    tag: string; // String!
    version: string; // String!
  };
  User: npm.User;
  Version: npm.Version;
}

export interface NexusGenInterfaces {
  Metadata: npm.Metadata;
  Node: NexusGenRootTypes['Package'] | NexusGenRootTypes['Version'];
}

export interface NexusGenUnions {}

export type NexusGenRootTypes = NexusGenInterfaces & NexusGenObjects;

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars;

export interface NexusGenFieldTypes {
  Distributable: {
    // field return type
    fileCount: number | null; // Int
    integrity: string | null; // String
    npmSignature: string | null; // String
    shasum: string; // String!
    tarball: NexusGenScalars['URL']; // URL!
    unpackagedSize: number | null; // Int
  };
  External: {
    // field return type
    type: string | null; // String
    url: NexusGenScalars['URL']; // URL!
  };
  File: {
    // field return type
    contentType: string | null; // String
    integrity: string | null; // String
    lastModified: NexusGenScalars['DateTime'] | null; // DateTime
    path: string; // String!
    size: number | null; // Int
    url: NexusGenScalars['URL'] | null; // URL
  };
  Package: {
    // field return type
    bugs: NexusGenRootTypes['External'] | null; // External
    createdAt: NexusGenScalars['DateTime']; // DateTime!
    description: string | null; // String
    distTags: NexusGenRootTypes['Tag'][] | null; // [Tag!]
    id: string; // ID!
    license: string | null; // String
    maintainers: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    modifiedAt: NexusGenScalars['DateTime']; // DateTime!
    name: string; // String!
    readme: string | null; // String
    readmeFilename: string | null; // String
    repository: NexusGenRootTypes['External'] | null; // External
    version: NexusGenRootTypes['Version'] | null; // Version
    versions: NexusGenRootTypes['Version'][] | null; // [Version!]
  };
  PackageConnection: {
    // field return type
    edges: Array<NexusGenRootTypes['PackageEdge'] | null> | null; // [PackageEdge]
    nodes: Array<NexusGenRootTypes['Package'] | null> | null; // [Package]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  };
  PackageEdge: {
    // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['Package'] | null; // Package
  };
  PageInfo: {
    // field return type
    endCursor: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor: string | null; // String
  };
  Query: {
    // field return type
    node: NexusGenRootTypes['Node'] | null; // Node
    package: NexusGenRootTypes['Package'] | null; // Package
    resolve: NexusGenRootTypes['Version'] | null; // Version
    search: NexusGenRootTypes['PackageConnection'] | null; // PackageConnection
  };
  Tag: {
    // field return type
    tag: string; // String!
    version: string; // String!
  };
  User: {
    // field return type
    email: NexusGenScalars['EmailAddress'] | null; // EmailAddress
    name: string; // String!
    url: NexusGenScalars['URL'] | null; // URL
  };
  Version: {
    // field return type
    author: NexusGenRootTypes['User']; // User!
    bugs: NexusGenRootTypes['External'] | null; // External
    description: string | null; // String
    dist: NexusGenRootTypes['Distributable']; // Distributable!
    files: Array<NexusGenRootTypes['File'] | null> | null; // [File]
    id: string; // ID!
    license: string | null; // String
    licenseText: string | null; // String
    main: string | null; // String
    maintainers: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    module: string | null; // String
    name: string; // String!
    repository: NexusGenRootTypes['External'] | null; // External
    version: string; // String!
  };
  Metadata: {
    // field return type
    bugs: NexusGenRootTypes['External'] | null; // External
    description: string | null; // String
    id: string; // ID!
    license: string | null; // String
    maintainers: Array<NexusGenRootTypes['User'] | null> | null; // [User]
    name: string; // String!
    repository: NexusGenRootTypes['External'] | null; // External
  };
  Node: {
    // field return type
    id: string; // ID!
  };
}

export interface NexusGenFieldTypeNames {
  Distributable: {
    // field return type name
    fileCount: 'Int';
    integrity: 'String';
    npmSignature: 'String';
    shasum: 'String';
    tarball: 'URL';
    unpackagedSize: 'Int';
  };
  External: {
    // field return type name
    type: 'String';
    url: 'URL';
  };
  File: {
    // field return type name
    contentType: 'String';
    integrity: 'String';
    lastModified: 'DateTime';
    path: 'String';
    size: 'Int';
    url: 'URL';
  };
  Package: {
    // field return type name
    bugs: 'External';
    createdAt: 'DateTime';
    description: 'String';
    distTags: 'Tag';
    id: 'ID';
    license: 'String';
    maintainers: 'User';
    modifiedAt: 'DateTime';
    name: 'String';
    readme: 'String';
    readmeFilename: 'String';
    repository: 'External';
    version: 'Version';
    versions: 'Version';
  };
  PackageConnection: {
    // field return type name
    edges: 'PackageEdge';
    nodes: 'Package';
    pageInfo: 'PageInfo';
  };
  PackageEdge: {
    // field return type name
    cursor: 'String';
    node: 'Package';
  };
  PageInfo: {
    // field return type name
    endCursor: 'String';
    hasNextPage: 'Boolean';
    hasPreviousPage: 'Boolean';
    startCursor: 'String';
  };
  Query: {
    // field return type name
    node: 'Node';
    package: 'Package';
    resolve: 'Version';
    search: 'PackageConnection';
  };
  Tag: {
    // field return type name
    tag: 'String';
    version: 'String';
  };
  User: {
    // field return type name
    email: 'EmailAddress';
    name: 'String';
    url: 'URL';
  };
  Version: {
    // field return type name
    author: 'User';
    bugs: 'External';
    description: 'String';
    dist: 'Distributable';
    files: 'File';
    id: 'ID';
    license: 'String';
    licenseText: 'String';
    main: 'String';
    maintainers: 'User';
    module: 'String';
    name: 'String';
    repository: 'External';
    version: 'String';
  };
  Metadata: {
    // field return type name
    bugs: 'External';
    description: 'String';
    id: 'ID';
    license: 'String';
    maintainers: 'User';
    name: 'String';
    repository: 'External';
  };
  Node: {
    // field return type name
    id: 'ID';
  };
}

export interface NexusGenArgTypes {
  Package: {
    version: {
      // args
      selector: string; // String!
    };
    versions: {
      // args
      limit?: number | null; // Int
      skip?: number | null; // Int
    };
  };
  Query: {
    node: {
      // args
      id: string; // ID!
    };
    package: {
      // args
      name: string; // String!
    };
    resolve: {
      // args
      name: string; // String!
      selector: string; // String!
    };
    search: {
      // args
      after?: string | null; // String
      first: number; // Int!
      query: string; // String!
    };
  };
  Version: {
    files: {
      // args
      limit?: number | null; // Int
      skip?: number | null; // Int
    };
  };
}

export interface NexusGenAbstractTypeMembers {
  Metadata: 'Package' | 'Version';
  Node: 'Package' | 'Version';
}

export interface NexusGenTypeInterfaces {
  Package: 'Metadata' | 'Node';
  Version: 'Metadata' | 'Node';
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = keyof NexusGenInterfaces;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = 'Metadata' | 'Node';

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false;
    resolveType: true;
    __typename: false;
  };
};

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes:
    | NexusGenTypes['inputNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['scalarNames'];
  allOutputTypes:
    | NexusGenTypes['objectNames']
    | NexusGenTypes['enumNames']
    | NexusGenTypes['unionNames']
    | NexusGenTypes['interfaceNames']
    | NexusGenTypes['scalarNames'];
  allNamedTypes:
    | NexusGenTypes['allInputTypes']
    | NexusGenTypes['allOutputTypes'];
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}

declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {}
  interface NexusGenPluginFieldConfig<
    TypeName extends string,
    FieldName extends string
  > {
    /**
     * Whether the type can be null
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    nullable?: boolean;
    /**
     * Whether the type is list of values, or just a single value.
     * If list is true, we assume the type is a list. If list is an array,
     * we'll assume that it's a list with the depth. The boolean indicates whether
     * the type is required (non-null), where true = nonNull, false = nullable.
     * @see declarativeWrappingPlugin
     */
    list?: true | boolean[];
    /**
     * Whether the type should be non null, `required: true` = `nullable: false`
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    required?: boolean;
    /**
    The TTL (time to live) for the given field’s cached results.
     */
    ttl?: number;
  }
  interface NexusGenPluginInputFieldConfig<
    TypeName extends string,
    FieldName extends string
  > {
    /**
     * Whether the type can be null
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    nullable?: boolean;
    /**
     * Whether the type is list of values, or just a single value.
     * If list is true, we assume the type is a list. If list is an array,
     * we'll assume that it's a list with the depth. The boolean indicates whether
     * the type is required (non-null), where true = nonNull, false = nullable.
     * @see declarativeWrappingPlugin
     */
    list?: true | boolean[];
    /**
     * Whether the type should be non null, `required: true` = `nullable: false`
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    required?: boolean;
  }
  interface NexusGenPluginSchemaConfig {}
  interface NexusGenPluginArgConfig {
    /**
     * Whether the type can be null
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    nullable?: boolean;
    /**
     * Whether the type is list of values, or just a single value.
     * If list is true, we assume the type is a list. If list is an array,
     * we'll assume that it's a list with the depth. The boolean indicates whether
     * the type is required (non-null), where true = nonNull, false = nullable.
     * @see declarativeWrappingPlugin
     */
    list?: true | boolean[];
    /**
     * Whether the type should be non null, `required: true` = `nullable: false`
     * @default (depends on whether nullability is configured in type or schema)
     * @see declarativeWrappingPlugin
     */
    required?: boolean;
  }
}
